name: "Wasted Lines Detector"
description: "Detects inefficient or overly complicated code and suggests improvements"
author: "Sudarshan"
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  github_app_id:
    description: "GitHub App ID"
    required: true
  github_private_key:
    description: "GitHub App Private Key"
    required: true
  ai_api_key:
    description: "API Key for AI-based code analysis"
    required: true

outputs:
  wasted_lines:
    description: "Number of wasted lines detected"

runs:
  using: "node20"
  main: "dist/index.js"