name: "Wasted Lines Detector"
description: "Detects inefficient or overly complicated code and suggests improvements"
author: "Sudarshan"
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  github_token:
    description: "GitHub Token for authentication"
    required: true

runs:
  using: "node20"
  main: "index.js"