name: Wasted Lines Detector

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  detect-wasted-lines:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Wasted Lines Detector
        uses: .
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
